-- Esta migration foi mesclada incorretamente durante um merge conflict.
-- A tabela BuildPronta já é criada pela migration add_price_history.
-- Mantida vazia para preservar o histórico de migrations já aplicado em produção.