version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15
    container_name: pcbuild_db
    restart: always
    environment:
      POSTGRES_USER: meusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: pcbuildmentor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: